### PR TITLE
Accounting for new elasticsearch org structure

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Getting the sub structure for each organization now that includes the
role.

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
works in test on dco.tw

**Comment by mrpatrickwest** [comment]
@olyerickson @am-e @zhonghao1014 @xgmachina @zednis 

Just need some folks to check over my work, review the changes.

**Comment by zhongh** [comment]
:checkered_flag: Looks working

**Comment by mrpatrickwest** [comment]
Examples:
https://dco.tw.rpi.edu/user/118/about

https://dco.tw.rpi.edu/user/7/about

**Comment by zhonghao1014** [comment]
Cannot access. And cannot login with my credentials.

**Comment by zhongh** [comment]
:+1:

**Comment by olyerickson** [comment]
On the "About" page, I suggest changing the label from "Teams" to "DCO Teams"

**Pull request merged**
